name: Build and Test (Maven)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Maven Build on ${{ matrix.os }} (JDK 21)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false           # keep other OS runs going if one fails
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin       # Eclipse Temurin builds of OpenJDK
          java-version: '21'
          cache: maven                # enables automatic ~/.m2 cache

      - name: Build and Test with Maven
        run: mvn -B verify            # -B = batch mode (no interactive output)
